app/app/urls.py
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from django.contrib import admin
from django.urls import path, include
from core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
    path('api/docs/',
         SpectacularSwaggerView.as_view(url_name='api-schema'),
         name='api-docs'),

    path('api/user', include('user.api_urls')),

    path('', core_views.home, name='home'),
    path('user/', include('user.urls', namespace='app-user')),
]

app/user/urls.py
"""
URL mappings for the user API
"""
from django.urls import path

from user import views


app_name = 'user'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

app/core/models.py
"""
Database models
"""
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)


class UserManager(BaseUserManager):
    """Manager for users"""

    def create_user(self,
                    email: str,
                    password: str = None,
                    **extra_fields):
        """Create, save and return a new user"""
        if not email:
            raise ValueError('User must have an email address.')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self.db)

        return user

    def create_superuser(self, email, password):
        """Create and return a new superuser."""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """User in the system"""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

app/user/forms.py
from django import forms
from django.utils.translation import gettext as _


class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(label=_('PasswordField'), widget=forms.PasswordInput, max_length=150)


class SignUpForm(forms.Form):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(label=_('PasswordField'), widget=forms.PasswordInput, max_length=150)
    password2 = forms.CharField(
        label=_('PasswordConfirmField'),
        widget=forms.PasswordInput,
        max_length=150,
        min_length=8,
    )

app/core/views.py
from django.shortcuts import render  # noqa


def home(response):
    return render(response, 'home.html', {})

app/user/views.py
"""
Views for the user API
"""
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.views import View
from django.utils.translation import gettext as _
from rest_framework import generics
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.settings import api_settings

from user.forms import LoginForm, SignUpForm
from user.serializers import (
    UserSerializer,
    AuthTokenSerializer,
)


# API views
class CreateUserView(generics.CreateAPIView):
    """Create a new user in the system."""
    serializer_class = UserSerializer


class CreateTokenView(ObtainAuthToken):
    """Create a new auth token for user."""
    serializer_class = AuthTokenSerializer
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES


# Web app views
class SignUpView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'signup.html', {
            'form': SignUpForm,
        })

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            password_conf = form.cleaned_data.get('password1')

            errors = []

            if password_conf != password:
                errors.append(_('SignUpIncorrectPasswordError'))
            if get_user_model().objects.filter(email=email).exists():
                errors.append(_('SignUpExistingEmailError'))

            have_errors = len(errors) > 0

            if not have_errors:
                try:
                    get_user_model().objects.create_user(email=email, password=password)
                except Exception as ex:
                    errors.extend([x[0] for x in ex.args])

            if have_errors:
                return render(request, 'signup.html', {
                    'have_errors': have_errors,
                    'errors': errors,
                    'form': UserCreationForm,
                })

            return render(request, 'signup_success.html')


class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'login.html', {
            'form': LoginForm,
        })

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(username=email, password=password)
        if user is None:
            return render(request, 'login.html', {
                'form': LoginForm,
                'errors': [_('LoginInvalidError')],
            })
        login(request, user)
        return redirect('home')


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('home')

app/core/templates/home.html
{% extends "base.html" %}

{% block content %}
    <p>Inicio</p>
{% endblock %}

app/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Test page{% endblock %}</title>
    {% block styles %}
    {% bootstrap_css %}
    {% endblock %}
</head>
<body>
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous">
    </script>
{% bootstrap_javascript %}
{% endblock %}

<p><a href="{%  url 'home' %}">Inicio</a></p>
{% if request.user.is_authenticated %}
    <p><a href="{% url 'app-user:logout' %}">Cerrar sesión</a></p>
{% else %}
    <p><a href="{% url 'app-user:login' %}">Iniciar sesión</a></p>
    <p><a href="{% url 'app-user:signup' %}">Crear cuenta</a></p>
{% endif %}

<div id="content">
    {% block content %}
        <h1>Main page</h1>
    {% endblock %}
</div>

</body>
</html>

app/user/templates/login.html
{% extends "base.html" %}

{% block content %}
    <p>{% trans 'LoginTitle' %}</p>
    <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button>{% trans 'LoginSubmitButton' %}</button>
    </form>
{% endblock %}

app/user/templates/signup.html
{% extends "base.html" %}

{% block content %}
    {% load i18n %}
    <p>{% trans 'SignUpHeading' %}</p>
    {% if have_errors %}
        <p>Signup error</p>
    {% endif %}
    <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button>{% trans 'SignUpSubmit' %}</button>
    </form>
{% endblock %}

app/user/templates/signup_success.html
{% extends "base.html" %}

{% block content %}
    {% load i18n %}
     <p>{% trans 'SignUpSuccessHeading' %}</p>
{% endblock %}